### ISSUE TITLE
List of todo items to complete before release first beta version

### ISSUE THREAD

**Issue by drio** [drio/segmentHunter#1]
Next milestone in #5 

## High priority
   - [ ] add help (home page?) to show people how to use the app
   - [x] fix location issues: if we cannot get the location, we can look into the segments coordinates.
   - [ ] Incorporate wind speed in scoring algorithm
   - [ ] Increase the time for which the strava token is valid. Check when it has expired and rerun oauth
   - [x] update icon in strava app config page
   - [x] refactor UI to add login/logout
   - [x] refine oauth process
   - [x] #2 Implement OAUTH in client
   - [x] #3  load data (strava/weather) and store in local storage
   - [x] Get current location when pulling weather data
   - [x] Use current location to determine map centering and zoom
   - [x] The weather gov API is not reliable; explore alternatives and prepare in case things fail
   - [x] ~~#4 Write production pipeline~~ decided to go to vercel
   - [x] Refactor segment logic so the Map component receives only a segments property and we do the local vs global in a dedicated file.
   - [x] Fix bug in Map where we don't associate score colors on load (see fixme entry).
   - [x] Get domain
- [ ] Add contact page
- [x] Write production pipeline
- [x] make the loading page pretty
- [ ] write tests for the different algorithm score cases

## Others
- [x] Incorporate profile image and username in UI
- [x] Allow hiding controls
- [ ] Improve time axis on slider so we show date details (like in windy)
