### ISSUE TITLE
Milestone 2: solid code

### ISSUE THREAD

**Issue by drio** [drio/segmentHunter#5]
In this milestone we want to stabilize the code to make changes easier. 

1. All the components have to deal with presentation. 
    - [ ] extract away the pieces of logic and moving it outside the component. 
    - [ ] maybe create a storybook for the components
2. The logic to get data is convoluted
    - [ ] refactor all the data loading and connect and expose it properly to the components. 
    Probably we want to use a data store (in rxjs). 
3. Write tests
    - [ ] for all the components (maybe storybook is enough). 
  

## From #1 
   - [ ] add help (home page?) to show people how to use the app
   - [ ] Incorporate wind speed in scoring algorithm
   - [ ] Increase the time for which the strava token is valid. Check when it has expired and rerun oauth
   - [ ] Add contact page
   - [ ] write tests for the different algorithm score cases
   - [ ] Improve time axis on slider so we show date details (like in windy)
